import { spawn } from 'child_process';
const fmcg = spawn('npx', ['tsx', 'target-deployer.js', 'fmcg'], { detached: true, stdio: 'ignore' });
fmcg.unref();
const partners = spawn('npx', ['tsx', 'target-deployer.js', 'partners'], { detached: true, stdio: 'ignore' });
partners.unref();
const merchant = spawn('npx', ['tsx', 'target-deployer.js', 'merchant'], { detached: true, stdio: 'ignore' });
merchant.unref();
const pwa = spawn('npx', ['tsx', 'target-deployer.js', 'pwa'], { detached: true, stdio: 'ignore' });
pwa.unref();
const admin = spawn('npx', ['tsx', 'target-deployer.js', 'admin'], { detached: true, stdio: 'ignore' });
admin.unref();
console.log('Deployments spawned in the background');
