export const TIER_CONFIG: Record<string, { poolRate: number; acceptCeiling: number; monthlyFeeKes: number }> = {
  BASIC:     { poolRate: 0.60, acceptCeiling: 0.30, monthlyFeeKes: 0    },
  CERTIFIED: { poolRate: 0.65, acceptCeiling: 0.35, monthlyFeeKes: 500  },
  HUB:       { poolRate: 0.70, acceptCeiling: 0.40, monthlyFeeKes: 1000 },
};

export const MIN_DENOMINATION = 5;

export const SKU_VARIANTS: Record<string, string[]> = {
  BR: ["400g", "600g", "700g"],
  ML: ["250ml", "500ml", "1L", "2L"],
  SG: ["500g", "1kg", "2kg", "5kg"],
  CO: ["500ml", "1L", "2L", "5L", "10L", "20L"],
  F:  ["1kg", "2kg", "5kg", "10kg", "25kg"],
};

export const SKU: Record<string, Record<string, string>> = {
  en: { BR: "SupaLoaf", ML: "Milk", SG: "Sugar", CO: "Cooking Oil", F: "Pembe Flour",
        BREAD: "SupaLoaf", MILK: "Milk", SUGAR: "Sugar", OIL: "Cooking Oil", FLOUR: "Pembe Flour",
        MAIZE: "Pembe Flour", COOKING: "Cooking Oil" },
  sw: { BR: "SupaLoaf", ML: "Maziwa", SG: "Sukari", CO: "Mafuta", F: "Pembe",
        BREAD: "SupaLoaf", MILK: "Maziwa", SUGAR: "Sukari", OIL: "Mafuta", FLOUR: "Pembe",
        MAIZE: "Pembe", COOKING: "Mafuta" },
};

export const T: Record<string, Record<string, string>> = {
  lang_pick:              { en: "Welcome to NX Loyalty\nChoose language:\n1 English\n2 Kiswahili", sw: "Karibu NX Loyalty\nChagua lugha:\n1 English\n2 Kiswahili" },
  main_menu:              { en: "Welcome to NX Loyalty\n1 Register\n2 Help\n3 Continue\n4 Recover Account\n5 Reset/Forgot PIN", sw: "Karibu NX Loyalty\n1 Jiandikishe\n2 Msaada\n3 Endelea\n4 Rudisha Akaunti\n5 Badili PIN" },
  help:                   { en: "NX lets you earn & spend tokens at certified kiosks.\nFirst purchase: 10% back. After: 5% back.\nCustomer NX expires 2 months after issuance.", sw: "NX hukuwezesha kupata na kutumia tokens katika maduka yaliyoidhinishwa.\n10% back mara ya kwanza. Baadaye 5%.\nNX ya wateja inaisha miezi 2." },
  not_registered:         { en: "Not registered. Please register first.", sw: "Bado hujasajiliwa. Jiandikishe kwanza." },
  terms:                  { en: "NX Terms:\nWe store your phone, name & national ID for loyalty rewards.\n1 Accept\n2 Reject", sw: "NX Terms:\nTutahifadhi namba, jina na kitambulisho chako.\n1 Kubali\n2 Kataa" },
  register_as:            { en: "Register as:\n1 Customer\n2 Merchant", sw: "Jisajili kama:\n1 Mteja\n2 Muuzaji" },
  must_accept:            { en: "You must accept terms to join NX.", sw: "Lazima ukubali vigezo ili kujiunga na NX." },
  name_empty:             { en: "Name cannot be empty.", sw: "Jina haliwezi kuwa tupu." },
  enter_biz_name:         { en: "Enter Business Name:", sw: "Weka Jina la Biashara:" },
  enter_location:         { en: "Enter Shop Location:", sw: "Weka Eneo la Duka:" },
  all_fields_required:    { en: "All fields are required.", sw: "Sehemu zote ni lazima." },
  welcome_customer:       { en: "Welcome {name}! Account active. Tokens: 0.", sw: "Karibu {name}! Akaunti iko tayari. Tokens: 0." },
  welcome_merchant:       { en: "Welcome {name}! Merchant account active.", sw: "Karibu {name}! Akaunti ya kuuza iko tayari." },
  shortcuts_customers:    { en: "Quick payments are only for customers.", sw: "Malipo ya haraka ni ya wateja pekee." },
  enter_name:             { en: "Enter your full name:", sw: "Weka jina lako kamili:" },
  enter_national_id:      { en: "Enter National ID number:", sw: "Weka namba ya kitambulisho (ID):" },
  set_pin:                { en: "Set 4-digit PIN:", sw: "Weka PIN ya tarakimu 4:" },
  reg_success:            { en: "Registration successful. Welcome to NX!", sw: "Ujisajili umefaulu. Karibu NX!" },
  reg_failed:             { en: "Registration failed. Try again.", sw: "Usajili umefeli. Jaribu tena." },
  enter_merchant_code:    { en: "Enter Merchant Code:", sw: "Weka namba ya muuzaji:" },
  enter_amount:           { en: "Enter Amount (KES):", sw: "Weka kiasi (KES):" },
  invalid_merchant_code:  { en: "Invalid Merchant Code.", sw: "Namba ya muuzaji sio sahihi." },
  invalid_amount:         { en: "Invalid Amount. Min 5 KES.", sw: "Kiasi kisichokubalika. Angalau KES 5." },
  insufficient_nx:        { en: "Insufficient NX.", sw: "Salio la NX halitoshi." },
  tx_failed:              { en: "Payment failed.", sw: "Malipo yamefeli." },
  merchant_menu:          { en: "CON Merchant Menu\n1 NX Wallet\n2 Restock\n3 Settings\n4 Confirm Delivery", sw: "CON Menyu ya Muuzaji\n1 NX Wallet\n2 Restock\n3 Settings\n4 Thibitisha Mzigo" },
  nx_wallet:              { en: "Code: {code}\nPool: {pool} NX\nUtil: {util}%\nBalance: {redeemed} NX\nSpendable ({rate}%): {usable} NX", sw: "Code: {code}\nPool: {pool} NX\nUtil: {util}%\nSalio: {redeemed} NX\nTumia ({rate}%): {usable} NX" },
  daily_summary:          { en: "END Daily Summary:\nTxns: {txns}\nCash: KSH {cash}\nVol: KSH {vol}\nNX redeemed: {red}\nNX earned: {earn}", sw: "END Muhtasari wa Leo:\nTxns: {txns}\nPesa: KSH {cash}\nJumla: KSH {vol}\nNX: {red}\nImepata: {earn}" },
  invoice_settled:        { en: "END Invoice settled!\nNX: {used}\nRetained: {ret}\nCash due: KSH {cash}\nPool +{pool_inc} NX", sw: "END Ankara imelipwa!\nNX: {used}\nImebaki: {ret}\nPesa: KSH {cash}\nPool +{pool_inc} NX" },
  enter_restock:          { en: "CON Enter restock order:\nBR*10, ML*5, SG*3\nor pembe 2kg*10", sw: "CON Weka oda:\nBR*10, ML*5, SG*3\nau pembe 2kg*10" },
  order_review:           { en: "CON Review Order:\n{items}\n1 Approve\n2 Decline", sw: "CON Hakiki Oda:\n{items}\n1 Thibitisha\n2 Kataa" },
  order_sent_detail:      { en: "END Order sent!\n{items}", sw: "END Oda imetumwa!\n{items}" },
  settings_menu:          { en: "CON Settings\n1 View Code\n2 Update Acceptance %\n3 My Tier", sw: "CON Settings\n1 View Code\n2 Update Acceptance %\n3 My Tier" },
  tier_status_detail:     { en: "END Tier: {tier}\nPool: {pool_pct}%\nAccept: {accept_pct}%\nFee: KES {fee}", sw: "END Tier: {tier}\nPool: {pool_pct}%\nKubali: {accept_pct}%\nAda: KES {fee}" },
  hub_menu:               { en: "CON Hub Menu\n1 Tier Status\n2 Enroll Sub-Merchant\n3 My Earnings", sw: "CON Menyu ya Hub\n1 Tier Status\n2 Enroll Sub-Merchant\n3 My Earnings" },
  no_pending_delivery:    { en: "END No pending deliveries.", sw: "END Hakuna mzigo unaosubiriwa." },
  confirm_delivery_prompt:{ en: "CON Confirm receipt of recent order?\n1 Yes\n2 No", sw: "CON Thibitisha kupokea mzigo?\n1 Ndio\n2 Hapana" },
  delivery_confirmed:     { en: "END Delivery confirmed.", sw: "END Mzigo umethibitishwa." },
  hub_stats:              { en: "END Hub: {count} sub-merchants, Tier: {tier}", sw: "END Hub: sub-merchants {count}, Tier: {tier}" },
  hub_earnings_detail:    { en: "END Month: {accrued} NX\nUnpaid: {unpaid} NX\nLast: {last}", sw: "END Mwezi: {accrued} NX\nHazijalipwa: {unpaid} NX\nMwisho: {last}" },
  recover_menu:           { en: "CON Enter your OLD phone number:", sw: "CON Weka namba yako ya zamani:" },
  new_pin:                { en: "CON Enter new 4-digit PIN:", sw: "CON Weka PIN mpya ya tarakimu 4:" },
  confirm_pin:            { en: "CON Confirm new 4-digit PIN:", sw: "CON Thibitisha PIN mpya:" },
  pin_reset_success:      { en: "END PIN reset successful.", sw: "END PIN imewekwa upya." },
  pin_reset_failed:       { en: "END PIN reset failed.", sw: "END PIN imefeli." },
  recover_success_detail: { en: "END Account recovered.\nCode: {code}", sw: "END Akaunti imerejeshwa.\nCode: {code}" },
  customer_confirm_pay:   { en: "CON Shop: {shop} ({code})\nAmount: KSH {amount}\nCash: KSH {cash} | NX: -{nx}\nEarn: +{earn} NX\nFee: {fee} NX\nTxn: {txn}\n1 Confirm\n2 Cancel", sw: "CON Duka: {shop} ({code})\nKiasi: KSH {amount}\nPesa: KSH {cash} | NX: -{nx}\nPata: +{earn} NX\nAda: {fee} NX\nTxn: {txn}\n1 Thibitisha\n2 Kataa" },
  customer_req_sent:      { en: "END Request sent.\nTxn: {txn}", sw: "END Ombi limetumwa.\nTxn: {txn}" },
  merchant_confirm_prompt:{ en: "CON Pending payment:\nFrom: {phone}\nAmount: KSH {amount}\nNX off: {nx}\n1 Approve\n2 Reject", sw: "CON Malipo yanayosubiri:\nKutoka: {phone}\nKiasi: KSH {amount}\nNX: {nx}\n1 Thibitisha\n2 Kataa" },
  request_sent:           { en: "Request sent. Txn: {txn}", sw: "Ombi limetumwa. Txn: {txn}" },
  enter_pin_reset_otp:    { en: "CON Enter the 6-digit code sent to your phone:", sw: "CON Weka namba ya siri ya tarakimu 6:" },
  otp_invalid_or_expired: { en: "END Code is invalid or expired. Dial in again to retry.", sw: "END Namba si sahihi au imeisha. Piga tena." },
  otp_send_failed:        { en: "END Could not send code. Try again shortly.", sw: "END Imeshindikana kutuma. Jaribu baadaye." },
  enter_login_pin:        { en: "CON Enter your 4-digit PIN:", sw: "CON Weka PIN yako ya tarakimu 4:" },
  invalid_login_pin:      { en: "END Incorrect PIN. Dial in again.", sw: "END PIN si sahihi. Piga tena." },
  log_basket_prompt:      { en: "CON Log what was sold?\n1 Yes\n2 Skip", sw: "CON Rekodi bidhaa zilizouzwa?\n1 Ndio\n2 Ruka" },
  log_basket_enter:       { en: "CON Enter items sold:\nFormat: BR*2, pembe 2kg@120*1\n(Name Variant@Price*Qty)", sw: "CON Weka bidhaa:\nMfumo: BR*2, pembe 2kg@120*1" },
  fraud_suspended:        { en: "END Account suspended: {reason}", sw: "END Akaunti imesimamishwa: {reason}" },
  error:                  { en: "An error occurred. Please try again.", sw: "Hitilafu imetokea. Tafadhali jaribu tena." },
};

const rawRestockPhone = Deno.env.get("RESTOCK_PHONE")?.trim() || "0781550151";
export const RESTOCK_PHONE = (rawRestockPhone && rawRestockPhone.length < 15 && /^\+?\d+$/.test(rawRestockPhone))
  ? rawRestockPhone : "0781550151";
